#!/usr/bin/env python3
"""
Simple script to compute any-optimal-64 metric from rollout results.

This script reads rollout evaluations generated by searchformer.rollout and computes:
- Solve rate: % of puzzles where at least 1 of 64 samples is correct
- Optimal rate: % of puzzles where at least 1 of 64 samples is optimal
"""

import argparse
import json
import logging
import os
from pathlib import Path

from searchformer.rollout import RolloutDataStore
from searchformer.sokoban import evaluate_rollout

logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s - %(asctime)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)


def compute_any_optimal_64(rollout_id: str, output_file: str = None):
    """
    Compute any-optimal-64 metric from rollout dataset.
    
    Args:
        rollout_id: ID of the rollout dataset
        output_file: Optional output JSON file
    """
    logging.info(f"Loading rollout dataset: {rollout_id}")
    
    # Load rollout dataset
    data_store = RolloutDataStore()
    rollout_dataset = data_store.load_by_id(rollout_id)
    
    # Get all test rollouts
    test_rollouts = list(rollout_dataset.rollout_test_it(rank=0, world_size=1))
    
    logging.info(f"Analyzing {len(test_rollouts)} test puzzles...")
    
    # Track results
    solved_puzzles = 0
    optimal_puzzles = 0
    puzzle_details = []
    
    for i, rollout in enumerate(test_rollouts):
        # Evaluate the rollout to get metrics
        rollout_eval_batch = evaluate_rollout(rollout)
        
        puzzle_id = rollout_eval_batch.id
        optimal_length = rollout_eval_batch.optimal_plan_length
        
        # Check if ANY of the 64 samples is correct
        any_correct = any(r.plan_correct for r in rollout_eval_batch.rollout)
        
        # Check if ANY of the 64 samples is optimal (correct + optimal length)
        any_optimal = any(
            r.plan_correct and r.plan_length == optimal_length 
            for r in rollout_eval_batch.rollout
        )
        
        # Count how many samples were correct
        num_correct = sum(1 for r in rollout_eval_batch.rollout if r.plan_correct)
        num_optimal = sum(
            1 for r in rollout_eval_batch.rollout 
            if r.plan_correct and r.plan_length == optimal_length
        )
        
        if any_correct:
            solved_puzzles += 1
        if any_optimal:
            optimal_puzzles += 1
        
        puzzle_details.append({
            "puzzle_id": puzzle_id,
            "solved": any_correct,
            "optimal_found": any_optimal,
            "num_correct_samples": num_correct,
            "num_optimal_samples": num_optimal,
            "total_samples": len(rollout_eval_batch.rollout),
            "optimal_length": optimal_length
        })
        
        # Progress update
        if (i + 1) % 50 == 0:
            current_solve_rate = solved_puzzles / (i + 1) * 100
            logging.info(
                f"Progress: {i+1}/{len(test_rollouts)} | "
                f"Solve rate: {current_solve_rate:.1f}%"
            )
    
    # Compute final metrics
    total_puzzles = len(test_rollouts)
    solve_rate = solved_puzzles / total_puzzles * 100 if total_puzzles > 0 else 0
    optimal_rate = optimal_puzzles / total_puzzles * 100 if total_puzzles > 0 else 0
    
    # Print results
    print("\n" + "=" * 70)
    print("ANY-OPTIMAL-64 EVALUATION RESULTS")
    print("=" * 70)
    print(f"Rollout ID: {rollout_id}")
    print(f"Total puzzles: {total_puzzles}")
    print(f"Puzzles solved (any of 64 correct): {solved_puzzles}")
    print(f"Puzzles with optimal solution: {optimal_puzzles}")
    print(f"Solve rate: {solve_rate:.2f}%")
    print(f"Optimal rate: {optimal_rate:.2f}%")
    print("=" * 70)
    
    # Save detailed results
    results = {
        "rollout_id": rollout_id,
        "total_puzzles": total_puzzles,
        "solved_puzzles": solved_puzzles,
        "optimal_puzzles": optimal_puzzles,
        "solve_rate": solve_rate,
        "optimal_rate": optimal_rate,
        "puzzle_details": puzzle_details
    }
    
    if not output_file:
        output_file = f"results_any_optimal_64_{rollout_id}.json"
    
    with open(output_file, 'w') as f:
        json.dump(results, f, indent=2)
    
    logging.info(f"Detailed results saved to: {output_file}")


def main():
    parser = argparse.ArgumentParser(
        description="Compute any-optimal-64 metric from rollout results"
    )
    parser.add_argument(
        "--rollout-id",
        required=True,
        help="Rollout dataset ID (generated by searchformer.rollout)"
    )
    parser.add_argument(
        "--local-data",
        default="local_data",
        help="Path to local data directory"
    )
    parser.add_argument(
        "--output",
        help="Output JSON file path"
    )
    
    args = parser.parse_args()
    
    # Set environment variable
    os.environ["LOCAL_DATA_PATH"] = args.local_data
    
    # Compute metric
    compute_any_optimal_64(args.rollout_id, args.output)


if __name__ == "__main__":
    main()
