#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=load_db
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:30:00
#SBATCH --output=slurm_outputs/slurm_output_%A.out

# --- modules / conda ---
module purge
module load 2024
module load Anaconda3/2024.06-1
source activate searchformer          # make sure this env has: pymongo, click, numpy, pygame (imported)

python eval_solve_rate.py --run-id "your-trained-model-id" --num-puzzles 200